import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import "./components/tasks/tasks.css"
import "./components/sidebar/sidebar.css"
import "./components/ui/ui.css"
import Providers from "./store/Providers";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}
      >
        <Providers>
          
          {children}
        </Providers>
      </body>
    </html>
  );
}
